# also gordie-ssh.kokovoko.org
Host gordie
  HostName 10.200.10.48
  User maeick
  IdentityFile ~/.ssh/andy-anywhere
  IdentitiesOnly yes
  StrictHostKeyChecking ask
  ForwardAgent yes

Host catfish
  HostName 10.1.1.21
  User root
  IdentityFile ~/.ssh/andy-anywhere
  IdentitiesOnly yes
  StrictHostKeyChecking ask
  ForwardAgent yes

Host jefferson
  HostName 10.225.10.43
  User maeick
  IdentityFile ~/.ssh/andy-anywhere
  IdentitiesOnly yes
  StrictHostKeyChecking ask
  ForwardAgent yes
